services:
  dat-parquet-handler:
    build: .
    image: dat-parquet-handler:latest
    env_file:
      - .env
    volumes:
      - ${SOURCE_DIR}:/input
      - ${DEST_DIR}:/output
    command: ["--help"]
