from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import pandas as pd


@dataclass(frozen=True)
class ConvertResult:
    source: Path
    destination: Path


def parse_columns(header_lines: list[str]) -> list[str] | None:
    prefix = "# Columns:"
    for line in header_lines:
        if line.startswith(prefix):
            cols = line[len(prefix):].strip()
            return [c.strip() for c in cols.split(",") if c.strip()]
    return None


def parse_data_row(line: str, columns: list[str]) -> list[str] | None:
    row = line.strip().split()

    if len(row) == len(columns):
        return row

    if "datetime" in columns and len(row) > len(columns):
        dt_idx = columns.index("datetime")
        extra = len(row) - len(columns)

        datetime_tokens = row[dt_idx:dt_idx + extra + 1]
        row = row[:dt_idx] + [" ".join(datetime_tokens)] + row[dt_idx + extra + 1:]
        if len(row) == len(columns):
            return row

    return None


def dat_to_dataframe(dat_file: Path) -> pd.DataFrame:
    header_lines: list[str] = []
    data_lines: list[str] = []

    with dat_file.open("rt", encoding="utf-8") as fobj:
        for raw_line in fobj:
            if not raw_line.strip():
                continue
            if raw_line.startswith("#"):
                header_lines.append(raw_line.strip())
            else:
                data_lines.append(raw_line.rstrip("\n"))

    columns = parse_columns(header_lines)
    if not columns:
        raise ValueError(f"Columns header not found in '{dat_file}'")

    rows: list[list[str]] = []
    for line in data_lines:
        row = parse_data_row(line, columns)
        if row is not None:
            rows.append(row)

    if not rows:
        raise ValueError(f"No valid data rows found in '{dat_file}'")

    df = pd.DataFrame(rows, columns=columns)

    for col in columns:
        if col == "datetime":
            continue
        df[col] = pd.to_numeric(df[col], errors="coerce")

    return df


def _format_value(value, col: str) -> str:
    if pd.isna(value):
        return "0"

    if col in {"tsn", "validity"} or col.endswith(".lli"):
        try:
            return str(int(round(float(value))))
        except (TypeError, ValueError):
            return "0"

    if isinstance(value, int):
        return str(value)

    try:
        numeric = float(value)
    except (TypeError, ValueError):
        return str(value)

    return f"{numeric:.12g}"


def dataframe_to_dat(df: pd.DataFrame, dat_file: Path) -> None:
    columns = list(df.columns)

    dat_file.parent.mkdir(parents=True, exist_ok=True)
    with dat_file.open("wt", encoding="utf-8") as fobj:
        fobj.write("# Generated by dat-parquet-handler\n")
        fobj.write(f"# Columns: {', '.join(columns)}\n")

        for row in df.itertuples(index=False, name=None):
            values = [_format_value(value, columns[idx]) for idx, value in enumerate(row)]
            fobj.write(" ".join(values) + "\n")


def convert_dat_to_parquet(src: Path, dst: Path, overwrite: bool = False) -> ConvertResult | None:
    if dst.exists() and not overwrite:
        return None

    dst.parent.mkdir(parents=True, exist_ok=True)
    dat_to_dataframe(src).to_parquet(dst, index=False, engine="pyarrow")
    return ConvertResult(source=src, destination=dst)


def convert_parquet_to_dat(src: Path, dst: Path, overwrite: bool = False) -> ConvertResult | None:
    if dst.exists() and not overwrite:
        return None

    df = pd.read_parquet(src, engine="pyarrow")
    dataframe_to_dat(df, dst)
    return ConvertResult(source=src, destination=dst)


def iter_files(root: Path, suffix: str) -> Iterable[Path]:
    suffix = suffix.lower()
    for path in root.rglob("*"):
        if path.is_file() and path.suffix.lower() == suffix:
            yield path


def convert_file(src: Path, dst: Path, direction: str, overwrite: bool = False) -> ConvertResult | None:
    if direction == "dat-to-parquet":
        return convert_dat_to_parquet(src, dst, overwrite=overwrite)
    if direction == "parquet-to-dat":
        return convert_parquet_to_dat(src, dst, overwrite=overwrite)
    raise ValueError(f"Unknown direction: {direction}")


def convert_tree(src_root: Path, dst_root: Path, direction: str, overwrite: bool = False) -> list[ConvertResult]:
    if direction == "dat-to-parquet":
        in_suffix = ".dat"
        out_suffix = ".parquet"
    elif direction == "parquet-to-dat":
        in_suffix = ".parquet"
        out_suffix = ".dat"
    else:
        raise ValueError(f"Unknown direction: {direction}")

    converted: list[ConvertResult] = []

    for src_file in iter_files(src_root, in_suffix):
        rel_path = src_file.relative_to(src_root)
        dst_file = (dst_root / rel_path).with_suffix(out_suffix)

        result = convert_file(src_file, dst_file, direction=direction, overwrite=overwrite)
        if result is not None:
            converted.append(result)

    return converted
